#!/bin/bash

echo "🔍 Diagnostic Pantone Variants"
echo "==============================="

echo "✅ VÉRIFICATIONS NÉCESSAIRES :"
echo ""
echo "1. 📊 Metaobject 'Pantone Color' :"
echo "   □ Contient bien 100+ entrées"
echo "   □ Champs : Code, Name, Hex remplis"
echo "   □ Storefront API access activé"
echo ""
echo "2. 🏷️ Metafield Produit :"
echo "   □ Nom : Product Color Variants" 
echo "   □ Type : List of metaobjects > Pantone Color"
echo "   □ Assigné aux produits concernés"
echo ""
echo "3. �� Variantes Produit :"
echo "   □ Option nommée 'Color' ou 'Couleur'"
echo "   □ Valeurs = Pantone Color > Name (exactement)"
echo "   □ Variantes créées et actives"
echo ""
echo "4. 📁 Templates :"
echo "   □ snippets/product-variant-color-selector.liquid uploaded"
echo "   □ {% render 'product-variant-color-selector', product: product %} ajouté"
echo ""
echo "🐛 PROBLÈMES COURANTS :"
echo "   • Noms différents : 'Black' vs 'Midnight Black'"
echo "   • Metafield non assigné au produit"
echo "   • Option variante nommée 'Couleur' mais template cherche 'Color'"
echo "   • Template non intégré dans product-form"
